apiVersion: v2
name: todo-app
description: AI-powered Todo application with Next.js frontend and FastAPI backend
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - todo
  - ai
  - chatbot
  - fastapi
  - nextjs
  - fullstack
  - kubernetes

home: https://github.com/yourusername/todo-app
sources:
  - https://github.com/yourusername/todo-app

maintainers:
  - name: Todo App Team
    email: team@todo-app.com

# Kubernetes version compatibility
kubeVersion: ">=1.25.0-0"

# No external dependencies - self-contained application
dependencies: []

annotations:
  category: Application
  licenses: MIT
