apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  better-auth-secret: {{ .Values.secrets.betterAuthSecret | quote }}
  openai-api-key: {{ .Values.secrets.openaiApiKey | quote }}
